name: Deploy Javadoc

permissions:
  contents: write
  
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy javadoc to Github Pages
        uses: jcm236/actions-publish-javadoc@3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          project: gradle
          deploy_dir: ${{ github.ref_name }}
